In [22]:
# Lambda Function:

add = lambda a,b: a+b
print(add(5,6))

11

In [23]:
square = lambda x: x*x
print(square(4))

16

In [24]:
# Using pandas with lambda & apply function:

import pandas as pd
df = pd.DataFrame({"temperature(F)" : [32,98.6,212,68]})
df
df['temperature(C)'] = df['temperature(F)'].apply(lambda x : (x-32)*5/9)
df

   temperature(F)  temperature(C)
0            32.0             0.0
1            98.6            37.0
2           212.0           100.0
3            68.0            20.0

In [25]:
# Using pandas with lambda & apply function:

import pandas as pd 
df = pd.DataFrame({'total_spent' : [100,2002,500,400]})
df ['is_high_value'] = df['total_spent'].apply(lambda x : 1 if x > 500 else 0)
df

   total_spent  is_high_value
0          100              0
1         2002              1
2          500              0
3          400              0

In [26]:
# Using pandas with lambda & filter function:

nums = [1,2,3,4,5,6,7,8,9,10]
result = filter(lambda x : x%2 == 0,nums)
print(list(result))

[2, 4, 6, 8, 10]